### PR TITLE
hotfix for gcc/4.8.x

### PR DESCRIPTION
**Pull request by mhsieh**
ref:
1. https://github.com/nlohmann/json/issues/259#issuecomment-227833643
2. https://github.com/nlohmann/json/commit/f86fe57c18c8e97ce3665380dc6cf46f8e42a36f

### CODE REVIEW

**Comment by mhsieh** [comment]
Don't merge just yet, we have not validated this.

**Comment by nlhepler** [comment]
@mhsieh where did this commit come from?

**Comment by nlhepler** [comment]
https://github.com/nlohmann/json#supported-compilers

@mhsieh gcc/4.8.x is emphatically unsupported by the json author due to bugs in that  version's implementation of the stdlib.

**Comment by pezmaster31** [comment]
That and this repo lives primarily in BB now, only mirrored here. We should place any PRs there, please.

**Comment by mhsieh** [comment]
I will remove the PR later, sorry about that.

**Comment by mhsieh** [comment]
@nlhepler - see that discussion thread, I think gcc/4.8.x might be still usable.

**Comment by nlhepler** [comment]
@mhsieh it does seem that way, but at the end of the day he vetoed it: https://github.com/nlohmann/json/pull/212#issuecomment-203528345

**Comment by mhsieh** [comment]
This will break the travis ci. /me sad panda

**Pull request closed without merging**
